name: 'Grab the latest Iosevka release'
on:
  push:
    branches:
      - actions
  schedule:
    - cron:  '* 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/auto-cancel-redundant-job@v1
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install downloader packages
        run: |
          cd scripts/downloader
          npm install

      - name: Download and commit fonts
        run: |
          cd scripts/downloader
          npm start

      - name: push changes to remote
        run: |
          git config --global user.name "Ayman Bagabas"
          git config --global user.email "ayman.bagabas@gmail.com"
          git tag -l | xargs -I{} git push origin {}
          git push origin HEAD:master
        if: always()
